name: Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /var/www/CrmSchedule/docker
            docker compose down
            cd ../
            git pull origin master
            cd docker
            docker compose build
#            docker compose up -d
